#!/usr/bin/env bash
#
# Terabras — container entrypoint.
#
# Runs on EVERY boot and must be idempotent: a fresh container and the 200th
# restart of an installed instance have to end in the same state. It deliberately
# does NOT run database migrations; upgrades are an explicit, operator-driven step
# (`php bin/console database:update`), so a restart can never mutate the schema.
set -euo pipefail

GLPI_ROOT="${GLPI_ROOT:-/var/www/glpi}"
GLPI_CONFIG_DIR="${GLPI_CONFIG_DIR:-/var/glpi/config}"
GLPI_VAR_DIR="${GLPI_VAR_DIR:-/var/glpi/files}"

log() { printf '[terabras-entrypoint] %s\n' "$*"; }

# ---------------------------------------------------------------------------
# 1. PHP limits, rendered from the environment.
#
# Centralising them here is what makes "100 MB uploads" a single knob: GLPI's
# advertised `document_max_size` is realigned to these values by the provisioning
# step, so the UI can never promise more than the stack accepts.
# ---------------------------------------------------------------------------
php_ini="/usr/local/etc/php/custom_conf.d/zz-terabras.ini"

# `session.cookie_secure` is the one directive we cannot decide up front: turning it
# on while the site is served over plain HTTP kills every session, and leaving it off
# while the site IS on HTTPS is what raises GLPI's "session.cookie_secure should be
# set to on" warning on the home page. Default to "auto" and let the provisioning
# step below resolve it from the instance's recorded public URL.
PHP_SESSION_COOKIE_SECURE="${PHP_SESSION_COOKIE_SECURE:-auto}"

write_php_ini() { # write_php_ini <cookie_secure 0|1>
  [ -w "$(dirname "$php_ini")" ] || return 1
  cat > "$php_ini" <<INI
; Generated by terabras-entrypoint from environment variables. Do not edit in place.
upload_max_filesize = ${PHP_UPLOAD_MAX_FILESIZE:-128M}
post_max_size = ${PHP_POST_MAX_SIZE:-144M}
memory_limit = ${PHP_MEMORY_LIMIT:-512M}
max_execution_time = ${PHP_MAX_EXECUTION_TIME:-300}
max_input_time = ${PHP_MAX_INPUT_TIME:-300}
max_file_uploads = ${PHP_MAX_FILE_UPLOADS:-50}

; Session cookie hardening. `samesite=Lax` is unconditional: it blocks the
; cross-origin POST case without breaking ordinary navigation, and satisfies the
; second half of GLPI's session-security requirement on every deployment.
session.cookie_httponly = 1
session.cookie_samesite = ${PHP_SESSION_COOKIE_SAMESITE:-Lax}
session.cookie_secure = ${1}
INI
}

case "$PHP_SESSION_COOKIE_SECURE" in
  auto) initial_cookie_secure=0 ;;
  1|on|true|yes|On|True|Yes) initial_cookie_secure=1 ;;
  *) initial_cookie_secure=0 ;;
esac

if write_php_ini "$initial_cookie_secure"; then
  log "PHP limits: upload=${PHP_UPLOAD_MAX_FILESIZE:-128M} post=${PHP_POST_MAX_SIZE:-144M} memory=${PHP_MEMORY_LIMIT:-512M}"
else
  log "WARNING: $(dirname "$php_ini") is not writable; PHP limits left at image defaults."
fi

# ---------------------------------------------------------------------------
# 1b. Render the Apache vhost, carrying the environment.
#
# GLPI resolves GLPI_CONFIG_DIR, GLPI_VAR_DIR and GLPI_ENVIRONMENT_TYPE with
# getenv() (see \Glpi\Application\SystemConfigurator), which under mod_php means
# Apache `SetEnv` — the mechanism GLPI documents. It has to live in the vhost: the
# base image's own vhost sets GLPI_ENVIRONMENT_TYPE=development, and a vhost-level
# SetEnv wins over a server-level one.
#
# Without this, a request served by Apache would look for config_db.php inside the
# application tree while the CLI looked on the volume — and the wizard would
# reappear after a restart.
# ---------------------------------------------------------------------------
vhost="/etc/apache2/sites-enabled/terabras.conf"
if [ -w "$(dirname "$vhost")" ]; then
  {
    echo "<VirtualHost *:80>"
    for var in GLPI_CONFIG_DIR GLPI_VAR_DIR GLPI_ENVIRONMENT_TYPE \
               TERABRAS_ADMIN_USER TERABRAS_ADMIN_PASSWORD TERABRAS_PLUGINS \
               TERABRAS_MIGRATE_FORMCREATOR TERABRAS_PUBLIC_URL; do
      value="${!var:-}"
      [ -n "$value" ] || continue
      printf '    SetEnv %s "%s"\n' "$var" "$value"
    done
    echo "    Include vhosts/glpi-common.conf"
    echo "</VirtualHost>"
  } > "$vhost"
  log "Rendered $vhost (environment: ${GLPI_ENVIRONMENT_TYPE:-production})."
else
  log "WARNING: cannot write $vhost; GLPI may not see GLPI_CONFIG_DIR over HTTP."
fi

# ---------------------------------------------------------------------------
# 2. Persistent directories.
#
# These are volume mount points. GLPI creates the `files/_*` subdirectories on
# demand, but the two roots must exist and be writable before anything boots.
# ---------------------------------------------------------------------------
mkdir -p "$GLPI_CONFIG_DIR" "$GLPI_VAR_DIR"

# Terabras translation overrides for the core catalogue. Copied rather than
# symlinked so the volume stays self-contained, and refreshed on every boot so an
# image upgrade ships its new strings.
if [ -d "$GLPI_ROOT/plugins/terabras/locales/core" ]; then
  mkdir -p "$GLPI_VAR_DIR/_locales/core"
  cp -f "$GLPI_ROOT/plugins/terabras/locales/core/"*.php "$GLPI_VAR_DIR/_locales/core/" 2>/dev/null || true
fi

# ---------------------------------------------------------------------------
# 2b. Precompiled stylesheets.
#
# Two problems solved at once:
#
#  * Staleness. GLPI caches compiled SCSS under a key built from the GLPI VERSION
#    (Html::compileScss -> FrontEnd::getVersionCacheKey), not from the stylesheet
#    contents, and that cache lives in GLPI_VAR_DIR — a volume that survives every
#    deploy. Shipping restyled CSS without bumping the GLPI version therefore had
#    no effect at all: the old CSS was served forever.
#  * A cold-start 500. Core `css/glpi.scss` takes ~20-30 s to compile, close
#    enough to max_execution_time that the first request after a cache wipe could
#    time out.
#
# `build:compile_scss` writes plain files under public/css_compiled/, which
# FrontEndAssetsExtension serves directly and in preference to the runtime
# compiler — so neither problem can occur. Guarded by a fingerprint of the SCSS
# sources so it only runs when the stylesheets actually changed.
#
# In an image that COPYs the source (rather than bind-mounting it), run this at
# BUILD time instead and this block becomes a no-op.
# ---------------------------------------------------------------------------
compiled_dir="$GLPI_ROOT/public/css_compiled"
if [ -w "$GLPI_ROOT/public" ] || [ -w "$compiled_dir" ]; then
  scss_fingerprint="$(find "$GLPI_ROOT/css" -name '*.scss' -type f -exec md5sum {} + 2>/dev/null | sort | md5sum | cut -d' ' -f1)"
  stamp="$compiled_dir/.terabras-fingerprint"
  if [ ! -f "$stamp" ] || [ "$(cat "$stamp" 2>/dev/null)" != "$scss_fingerprint" ]; then
    log "Stylesheets changed; precompiling SCSS (this takes ~20s, once)…"
    if php "$GLPI_ROOT/bin/console" --no-interaction build:compile_scss >/dev/null 2>&1; then
      mkdir -p "$compiled_dir" && printf '%s' "$scss_fingerprint" > "$stamp"
      log "SCSS precompiled."
    else
      log "WARNING: SCSS precompilation failed; the runtime compiler will be used instead."
    fi
  fi
else
  log "Read-only source tree: skipping SCSS precompilation (compile it at image build time)."
fi

# ---------------------------------------------------------------------------
# 3. Provisioning, only once the instance is actually installed.
#
# No config_db.php means the operator has not run the wizard yet: start the web
# server so they can. We never create, move or delete that file here — it is the
# single artefact that says "this instance is installed", and it lives on the
# config volume precisely so a container replacement cannot lose it.
# ---------------------------------------------------------------------------
if [ -f "$GLPI_CONFIG_DIR/config_db.php" ]; then
  log "Installed instance detected; waiting for the database…"
  db_ready=0
  for _ in $(seq 1 60); do
    # Read the credentials straight out of config_db.php rather than booting GLPI:
    # the kernel is exactly what we cannot rely on until the database answers.
    if php -r '
        $src = @file_get_contents($argv[1]);
        preg_match_all("/\\$(dbhost|dbuser|dbpassword|dbdefault)\\s*=\\s*\x27([^\x27]*)\x27/", (string) $src, $m, PREG_SET_ORDER);
        $c = [];
        foreach ($m as $i) { $c[$i[1]] = $i[2]; }
        if (count($c) < 4) { exit(1); }
        mysqli_report(MYSQLI_REPORT_OFF);
        $link = @new mysqli($c["dbhost"], $c["dbuser"], $c["dbpassword"], $c["dbdefault"]);
        exit($link->connect_errno ? 1 : 0);
      ' "$GLPI_CONFIG_DIR/config_db.php" >/dev/null 2>&1; then
      db_ready=1
      break
    fi
    sleep 2
  done

  if [ "$db_ready" -ne 1 ]; then
    log "WARNING: database unreachable after 120s; skipping provisioning and starting the web server anyway."
  else
    # The branding plugin must be installed AND active before its console command is
    # discoverable (CommandLoader only scans activated plugins). Both commands are
    # no-ops once that is true, so this stays cheap on every subsequent boot.
    php "$GLPI_ROOT/bin/console" --no-interaction plugin:install terabras  >/dev/null 2>&1 || true
    php "$GLPI_ROOT/bin/console" --no-interaction plugin:activate terabras >/dev/null 2>&1 || true

    log "Applying Terabras provisioning (idempotent)…"
    provisioning_output="$(php "$GLPI_ROOT/bin/console" --no-interaction plugins:terabras:postinstall 2>&1)" \
      || log "WARNING: provisioning did not complete; the instance is still usable. See the log below."
    printf '%s\n' "$provisioning_output" | grep -v '^TERABRAS_PUBLIC_HTTPS=' || true

    # Provisioning reports whether the recorded public URL is https://. Apache has
    # not started yet, so re-rendering the ini here still takes effect on the first
    # request.
    if [ "$PHP_SESSION_COOKIE_SECURE" = "auto" ] \
       && printf '%s' "$provisioning_output" | grep -q '^TERABRAS_PUBLIC_HTTPS=1'; then
      if write_php_ini 1; then
        log "Public URL is HTTPS: session.cookie_secure enabled."
      fi
    fi
  fi
else
  log "No $GLPI_CONFIG_DIR/config_db.php: instance not installed yet, serving the setup wizard."
fi

exec docker-php-entrypoint "$@"
